### ISSUE TITLE
No defaults for multiple choices / checkboxes?

### ISSUE THREAD

**Issue by gilbh** [PFython/easypypi#31]
Is there a reason why the multiple choices and checkboxes are not remembered from one `review()` cycle to the next? It is a lot of labor to re-enter these every time.
![image](https://user-images.githubusercontent.com/39532610/102712824-cb187180-4291-11eb-82b4-5f4d1f53f201.png)

**Comment by gilbh** [comment]
This might be identical to issue #4

**Comment by PFython** [comment]
No GOOD reason Gil!  Just a gap in my skills which Ruud has helped me with.  I now just need to implement and test.  Please bear with me...
