### ISSUE TITLE
Pre-select checkboxes and radio buttons

### ISSUE THREAD

**Issue by PFython** [PFython/easypypi#4]
Classifier data is currently being lost because `easyPyPI` doesn't pre-select checkboxes (or radio button in the case of License selection).  If the user selects nothing or cancels at this point, `self.classifiers` is reset to nothing which is annoying if you've taken time and care choosing exactly the right classifiers previously!

This issue is linked to https://github.com/PFython/easypypi/issues/2

**Comment by salabim** [comment]
Have a look at my mockup code, which keeps the selections.

**Comment by PFython** [comment]
I see you're an early riser/later sleeper too!  Many thanks for these suggestions Ruud.  Looking forward to getting my head around the checkbox code shortly!
